/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dprsatisprogrami;
import dprsatisprogrami.satisyap;
import dprsatisprogrami.satislar;
import dprsatisprogrami.urunler;
import dprsatisprogrami.kullanicilar;
import dprsatisprogrami.musteriler;
/**
 *
 * @author tayyi
 */
public class anasayfa extends javax.swing.JFrame {

    /**
     * Creates new form anasayfa
     */
    public anasayfa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_urenler = new javax.swing.JButton();
        btn_musteriler = new javax.swing.JButton();
        btn_satisyap = new javax.swing.JButton();
        btn_satislar = new javax.swing.JButton();
        btn_kullanicilar = new javax.swing.JButton();
        btn_cikis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/dprLogo.png"))); // NOI18N

        btn_urenler.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btn_urenler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/urunler64.png"))); // NOI18N
        btn_urenler.setText("URUNLER");
        btn_urenler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_urenler.setPreferredSize(new java.awt.Dimension(130, 100));
        btn_urenler.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_urenler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_urenlerActionPerformed(evt);
            }
        });

        btn_musteriler.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btn_musteriler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/musteriler64.png"))); // NOI18N
        btn_musteriler.setText("MUSTERİLER");
        btn_musteriler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_musteriler.setPreferredSize(new java.awt.Dimension(130, 100));
        btn_musteriler.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_musteriler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_musterilerActionPerformed(evt);
            }
        });

        btn_satisyap.setBackground(new java.awt.Color(255, 153, 153));
        btn_satisyap.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btn_satisyap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/satisyap64.png"))); // NOI18N
        btn_satisyap.setText("SATIŞ YAP");
        btn_satisyap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_satisyap.setPreferredSize(new java.awt.Dimension(130, 100));
        btn_satisyap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_satisyap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_satisyapActionPerformed(evt);
            }
        });

        btn_satislar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btn_satislar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/satislar64.png"))); // NOI18N
        btn_satislar.setText("SATIŞLAR");
        btn_satislar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_satislar.setPreferredSize(new java.awt.Dimension(130, 100));
        btn_satislar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_satislar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_satislarActionPerformed(evt);
            }
        });

        btn_kullanicilar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btn_kullanicilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/kullanicilar64.png"))); // NOI18N
        btn_kullanicilar.setText("KULLANICILAR");
        btn_kullanicilar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_kullanicilar.setPreferredSize(new java.awt.Dimension(130, 100));
        btn_kullanicilar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_kullanicilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kullanicilarActionPerformed(evt);
            }
        });

        btn_cikis.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btn_cikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/cikis264.png"))); // NOI18N
        btn_cikis.setText("ÇIKIŞ");
        btn_cikis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cikis.setPreferredSize(new java.awt.Dimension(130, 100));
        btn_cikis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_musteriler, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_urenler, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_satisyap, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btn_satislar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_kullanicilar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_satislar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btn_kullanicilar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_satisyap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btn_musteriler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btn_urenler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_musterilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_musterilerActionPerformed
       musteriler g=new musteriler();
       g.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btn_musterilerActionPerformed

    private void btn_urenlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_urenlerActionPerformed
       urunler g=new urunler();
       g.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btn_urenlerActionPerformed

    private void btn_satislarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_satislarActionPerformed
        satislar g=new satislar();
       g.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btn_satislarActionPerformed

    private void btn_kullanicilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kullanicilarActionPerformed
        kullanicilar g=new kullanicilar();
       g.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btn_kullanicilarActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void btn_satisyapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_satisyapActionPerformed
        satisyap g=new satisyap();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_satisyapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_kullanicilar;
    private javax.swing.JButton btn_musteriler;
    private javax.swing.JButton btn_satislar;
    private javax.swing.JButton btn_satisyap;
    private javax.swing.JButton btn_urenler;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
