/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dprsatisprogrami;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tayyi
 */
public class kullanicilar extends javax.swing.JFrame {
    String kulad="root";
    String parola="";
    String db_name="petshop";
    String host="localhost";
    int port=3306;
    Connection conn=null;
    Statement st=null;
    ResultSet rs=null;
    DefaultTableModel model;
    String url =null;
    /**
     * Creates new form kullanicilar
     */
    public kullanicilar() {
        initComponents();
        Baglantiac();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_kullanici = new javax.swing.JTable();
        btn_ekle = new javax.swing.JButton();
        btn_duzenle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ara = new javax.swing.JTextField();
        btn_ara = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_kullaniciid = new javax.swing.JTextField();
        txt_kullaniciadi = new javax.swing.JTextField();
        txt_sifre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_Getir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_kullanici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KULLANICI ID", "KULLANICI ADI", "SIFRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_kullanici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_kullaniciMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_kullanici);

        btn_ekle.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btn_ekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/ekle24.png"))); // NOI18N
        btn_ekle.setText("EKLE");
        btn_ekle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ekle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        btn_duzenle.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        btn_duzenle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/duzenle24.png"))); // NOI18N
        btn_duzenle.setText("DÜZENLE");
        btn_duzenle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_duzenle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_duzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_duzenleActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KULLANICI ARA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 10))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        jLabel1.setText("KULLANICI ADI");

        btn_ara.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        btn_ara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/ara24.png"))); // NOI18N
        btn_ara.setText("ARA");
        btn_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_araActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ara))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ara, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/cikis64.png"))); // NOI18N
        jButton3.setText("ANA SAYFAYA DÖN ");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel2.setText("Kullaniciid :");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel3.setText("Kullanici Adı :");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel4.setText("Sifre :");

        btn_Getir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/musteriler64.png"))); // NOI18N
        btn_Getir.setText("Kullanıcı Getir");
        btn_Getir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Getir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Getir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GetirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_kullaniciid)
                                    .addComponent(txt_kullaniciadi)
                                    .addComponent(txt_sifre, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Getir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_duzenle))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_kullaniciid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addComponent(txt_kullaniciadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Getir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_duzenle))
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Baglantiac(){
    url="jdbc:mysql://"+host+":"+port+"/"+db_name+"?CharacterEncoding=utf8";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection(url,kulad,parola);
            st=conn.createStatement();
            System.out.println("Bağlantı Başarılı");
        } catch (ClassNotFoundException ex) {
            System.out.println("Driver Bulunamadı");
        } catch (SQLException ex) {  
            System.out.println("Bağlantı Hatası");
        }

    }
    public void BaglantiKapat(){
        try {
            conn.close();
        } catch (Exception e) {
            System.out.println("BAĞLANTI KAPATIRKEN HATA OLUSTU");
        }
    
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        anasayfa g=new anasayfa();
       g.setVisible(true);
       this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_GetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GetirActionPerformed
        try {
            st = conn.createStatement();
            rs=st.executeQuery("Select * from kullanici");
            model=(DefaultTableModel)table_kullanici.getModel();
            model.getDataVector().removeAllElements();
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString("kullaniciid"),rs.getString("kullaniciadi"),rs.getString("sifre")});
            }
            rs.first();
            txt_kullaniciid.setText(rs.getString("kullaniciid"));
            txt_kullaniciadi.setText(rs.getString("kullaniciadi"));
            txt_sifre.setText(rs.getString("sifre"));

        } catch (SQLException ex) {
            Logger.getLogger(kullanicilar.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btn_GetirActionPerformed

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        kullaniciislemleri g=new kullaniciislemleri();
       g.setVisible(true);
       this.setVisible(false);  
    }//GEN-LAST:event_btn_ekleActionPerformed

    private void btn_duzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_duzenleActionPerformed
         String sordu="Update kullanici set kullaniciadi=?, sifre=? where kullaniciid=?";
        try {
            PreparedStatement pst = conn.prepareStatement(sordu);  
            pst.setString(3,txt_kullaniciid.getText());
            pst.setString(1,txt_kullaniciadi.getText());
            pst.setString(2,txt_sifre.getText());

           int sonuc = pst.executeUpdate();
           if (sonuc >0){
               JOptionPane.showMessageDialog(this, "Güncelleme başarılı");
           }
           else {JOptionPane.showMessageDialog(this, "Güncelleme başarısız");
           }
           tablodoldur();
            
        } catch (SQLException ex) {
            Logger.getLogger(musteriler.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btn_duzenleActionPerformed

    private void table_kullaniciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_kullaniciMouseClicked
        DefaultTableModel model=(DefaultTableModel)table_kullanici.getModel();
        int secilensatir=table_kullanici.getSelectedRow();
        txt_kullaniciid.setText(model.getValueAt(secilensatir, 0).toString());
        txt_kullaniciadi.setText(model.getValueAt(secilensatir, 1).toString());
        txt_sifre.setText(model.getValueAt(secilensatir, 2).toString());

    }//GEN-LAST:event_table_kullaniciMouseClicked

    private void btn_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_araActionPerformed
    String b=txt_ara.getText();
        DefaultTableModel model=(DefaultTableModel)table_kullanici.getModel();
        model.getDataVector().removeAllElements();
        String sorgu="Select * from kullanici where kullaniciadi='"+b+"'";
        try{
        rs=st.executeQuery(sorgu);
        while(rs.next()){
            model.addRow(new Object[]{rs.getString("kullaniciid"),rs.getString("kullaniciadi"),rs.getString("sifre")});
            
        }
        }
        catch (SQLException ex) {
           Logger.getLogger(urunler.class.getName()).log(Level.SEVERE, null, ex);
       }
                       
    }//GEN-LAST:event_btn_araActionPerformed
public void tablodoldur(){
    
        try {
            st = conn.createStatement();
            rs = st.executeQuery("Select * from kullanici");
            model = (DefaultTableModel)table_kullanici.getModel();
            model.getDataVector().removeAllElements();
            while (rs.next()) {                
                model.addRow(new Object[]{rs.getString("kullaniciid"),rs.getString("kullaniciadi"),rs.getString("sifre")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanicilar.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kullanicilar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kullanicilar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kullanicilar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kullanicilar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kullanicilar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Getir;
    private javax.swing.JButton btn_ara;
    private javax.swing.JButton btn_duzenle;
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_kullanici;
    private javax.swing.JTextField txt_ara;
    private javax.swing.JTextField txt_kullaniciadi;
    private javax.swing.JTextField txt_kullaniciid;
    private javax.swing.JTextField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
