/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dprsatisprogrami;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tayyi
 */
public class urunler extends javax.swing.JFrame {
    String kulad="root";
    String parola="";
    String db_name="petshop";
    String host="localhost";
    int port=3306;
    Connection conn=null;
    Statement st=null;
    ResultSet rs=null;
    DefaultTableModel model;
    String url =null;
    DefaultComboBoxModel cmd=new DefaultComboBoxModel();
    
    /**
    /**
     * Creates new form urunler
     */
    public urunler() {
        initComponents();
        Baglantiac();
    }
public void Baglantiac(){
    url="jdbc:mysql://"+host+":"+port+"/"+db_name+"?CharacterEncoding=utf8";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection(url,kulad,parola);
            st=conn.createStatement();
            System.out.println("Bağlantı Başarılı");
        } catch (ClassNotFoundException ex) {
            System.out.println("Driver Bulunamadı");
        } catch (SQLException ex) {  
            System.out.println("Bağlantı Hatası");
        }

    }
    public void BaglantiKapat(){
        try {
            conn.close();
        } catch (Exception e) {
            System.out.println("BAĞLANTI KAPATIRKEN HATA OLUSTU");
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_urunler = new javax.swing.JTable();
        txt_barkod = new javax.swing.JTextField();
        txt_urun = new javax.swing.JTextField();
        txt_firma = new javax.swing.JTextField();
        txt_stok = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmb_urunler = new javax.swing.JComboBox();
        btn_urunekle = new javax.swing.JButton();
        btn_urunduzenle = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ara = new javax.swing.JTextField();
        btn_ara = new javax.swing.JButton();
        btn_Anasayfa = new javax.swing.JButton();
        btn_urungetir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ÜRÜNLER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 10))); // NOI18N

        table_urunler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BARKOD", "ÜRÜN", "FİRMA", "STOK", "tc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_urunler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_urunlerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_urunler);

        jLabel2.setText("Barkod");

        jLabel3.setText("Ürün");

        jLabel4.setText("Firma");

        jLabel5.setText("Stok");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_urun)
                            .addComponent(txt_firma)
                            .addComponent(txt_stok, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(txt_barkod))
                        .addGap(86, 86, 86)
                        .addComponent(cmb_urunler, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_barkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_urunler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_urun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_firma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        btn_urunekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/ekle24.png"))); // NOI18N
        btn_urunekle.setText("URUN EKLE");
        btn_urunekle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_urunekle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_urunekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_urunekleActionPerformed(evt);
            }
        });

        btn_urunduzenle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/duzenle24.png"))); // NOI18N
        btn_urunduzenle.setText("Güncelle");
        btn_urunduzenle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_urunduzenle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_urunduzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_urunduzenleActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ÜRÜN ARA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 10))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 10)); // NOI18N
        jLabel1.setText("ÜRÜN");

        btn_ara.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        btn_ara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/ara24.png"))); // NOI18N
        btn_ara.setText("ARA");
        btn_ara.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ara.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_araActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ara, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_Anasayfa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/cikis64.png"))); // NOI18N
        btn_Anasayfa.setText("ANA SAYFAYA DÖN ");
        btn_Anasayfa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Anasayfa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnasayfaActionPerformed(evt);
            }
        });

        btn_urungetir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dprsatisprogrami/resimveicon/urunler64.png"))); // NOI18N
        btn_urungetir.setText("ÜRÜNLERİ LİSTELE");
        btn_urungetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_urungetirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_urunekle, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_urunduzenle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_urungetir, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Anasayfa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_urunduzenle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_urunekle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_urungetir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Anasayfa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AnasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnasayfaActionPerformed
        anasayfa g=new anasayfa();
       g.setVisible(true);
       this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AnasayfaActionPerformed

    private void btn_urungetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_urungetirActionPerformed
        
        try {
            st = conn.createStatement();
            rs=st.executeQuery("Select musteri.tc, urun.barkod,tanim,firma,stok,tc From urun INNER JOIN musteri");
            model=(DefaultTableModel)table_urunler.getModel();
            model.getDataVector().removeAllElements();
            cmd.removeAllElements();
            while (rs.next()) {                
                model.addRow(new Object[]{rs.getString("barkod"),rs.getString("tanim"),rs.getString("firma"),rs.getInt("stok"),rs.getString("tc")});
                cmd.addElement(rs.getString("firma"));
            }
            cmb_urunler.setModel(cmd);
            rs.first();
            txt_barkod.setText(rs.getString("barkod"));
            txt_urun.setText(rs.getString("tanim"));
            txt_firma.setText(rs.getString("firma"));
            
           
        String stok =  String.valueOf(rs.getInt("stok"));
            txt_stok.setText(stok);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(musteriler.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btn_urungetirActionPerformed
    public void tablodoldur(){
    
        try {
            st = conn.createStatement();
            rs = st.executeQuery("Select * from urun");
            model = (DefaultTableModel)table_urunler.getModel();
            model.getDataVector().removeAllElements();
            while (rs.next()) {                
                model.addRow(new Object[]{rs.getString("barkod"),rs.getString("tanim"),rs.getString("firma"),rs.getString("stok")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(urunler.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    private void btn_urunduzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_urunduzenleActionPerformed
       String sordu="Update urun set tanim=?, firma=?,stok=? where barkod=?";
       
     int stok =  Integer.parseInt(txt_stok.getText());
        try {
            PreparedStatement pst = conn.prepareStatement(sordu);
            
            pst.setString(1, txt_urun.getText());
            pst.setString(2,txt_firma.getText());
//            pst.setString(3,txt_stok.getText());
            pst.setString(4, txt_barkod.getText());
            pst.setInt(3,stok);
           int sonuc = pst.executeUpdate();
           if (sonuc >0){
               JOptionPane.showMessageDialog(this, "Güncelleme başarılı");
           }
           tablodoldur();
            
        } catch (SQLException ex) {
            Logger.getLogger(urunler.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btn_urunduzenleActionPerformed

    private void btn_urunekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_urunekleActionPerformed
       urunislemleri g=new urunislemleri();
       g.setVisible(true);
       this.setVisible(false);  

//        String sordu="Insert into urun(barkod,tanim,firma,stok) values(?,?,?,?)";
//       
//     int stok =  Integer.parseInt(txt_stok.getText());
//        try {
//            PreparedStatement pst = conn.prepareStatement(sordu);
//            
//            pst.setString(1, txt_barkod.getText());
//            pst.setString(2,txt_urun.getText());
//            pst.setString(3, txt_firma.getText());
//            pst.setInt(4,stok);
//           int sonuc = pst.executeUpdate();
//           if (sonuc >0){
//               JOptionPane.showMessageDialog(this, "Ekleme başarılı");
//           }
//           tablodoldur();
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(urunler.class.getName()).log(Level.SEVERE,null,ex);
//        }
    }//GEN-LAST:event_btn_urunekleActionPerformed

    private void table_urunlerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_urunlerMouseClicked
         DefaultTableModel model=(DefaultTableModel)table_urunler.getModel();
        int secilensatir=table_urunler.getSelectedRow();
        txt_barkod.setText(model.getValueAt(secilensatir, 0).toString());
        txt_urun.setText(model.getValueAt(secilensatir, 1).toString());
        txt_firma.setText(model.getValueAt(secilensatir, 2).toString());
        txt_stok.setText(model.getValueAt(secilensatir, 3).toString());
    }//GEN-LAST:event_table_urunlerMouseClicked

    private void btn_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_araActionPerformed
    String b=txt_ara.getText();
        DefaultTableModel model=(DefaultTableModel)table_urunler.getModel();
        model.getDataVector().removeAllElements();
        String sorgu="Select * from urun where tanim='"+b+"'";
        try{
        rs=st.executeQuery(sorgu);
        while(rs.next()){
            model.addRow(new Object[]{rs.getString("barkod"),rs.getString("tanim"),rs.getString("firma"),rs.getString("stok")});
            
            txt_urun.setText(rs.getString("tanim"));
            txt_firma.setText(rs.getString("firma"));
            txt_stok.setText(rs.getString("stok"));
            txt_barkod.setText(rs.getString("barkod"));
        }
        }
        catch (SQLException ex) {
           Logger.getLogger(urunler.class.getName()).log(Level.SEVERE, null, ex);
       }
                
    }//GEN-LAST:event_btn_araActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(urunler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(urunler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(urunler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(urunler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new urunler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Anasayfa;
    private javax.swing.JButton btn_ara;
    private javax.swing.JButton btn_urunduzenle;
    private javax.swing.JButton btn_urunekle;
    private javax.swing.JButton btn_urungetir;
    private javax.swing.JComboBox cmb_urunler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_urunler;
    private javax.swing.JTextField txt_ara;
    private javax.swing.JTextField txt_barkod;
    private javax.swing.JTextField txt_firma;
    private javax.swing.JTextField txt_stok;
    private javax.swing.JTextField txt_urun;
    // End of variables declaration//GEN-END:variables

}